language: c
sudo: required
install:
  - sudo add-apt-repository --yes ppa:avsm/ppa
  - sudo apt-get --assume-yes update
  - sudo apt-get --assume-yes install opam
  - opam init --yes --compiler=ocaml-base-compiler.$OCAML_VERSION --switch=ocaml-base-compiler.$OCAML_VERSION
script:
  - opam pin --yes add re .
  - opam install --yes re
  - opam remove --yes re
env:
  global:
  - PACKAGE=re
  matrix:
  - OCAML_VERSION=4.02.3
os:
  - linux
