language: c
sudo: required
install:
  - opam init
  - opam switch create ocaml-base-compiler.$OCAML_VERSION || true
script:
  - opam pin add my-package .
  - opam install my-package
  - opam remove my-package
env:
  global:
  - PACKAGE=re
  matrix:
  - OCAML_VERSION=4.02
os:
  - linux
